fix: caddy 2.10 does panic due to catch all next to hostname
The catch-all existed only to ease debugging so it can be removed.

> Error: adapting config using caddyfile: automation policy from site block is also default/catch-all policy because of key without hostname, and the two are in conflict: []certmagic.Issuer(nil) != []certmagic.Issuer{(*caddytls.ACMEIssuer)(0xc0007e0b48)}